
GLA:
  num_nodes: 3834
  in_steps: 12
  out_steps: 12

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  day_of_week: True
  
  lr: 0.001
  weight_decay: 0.0001
  milestones: [15, 30, 40]
  lr_decay_rate: 0.1
  batch_size:  64
  max_epochs: 300
  early_stop: 30
  use_cl: False
  cl_step_size: 2300

  model_args:
    num_nodes: 3834
    in_dim:  3
    model_dim:  128
    time:  96
    in_len:  12
    out_len:  12
    num_heads:  4
    pool_size:  32
    attn_drop:  0.1
    proj_drop:  0.15

SD:
  num_nodes: 716
  in_steps: 12
  out_steps: 12

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  day_of_week: True
  
  lr: 0.001
  weight_decay: 0.0001
  milestones: [15, 30, 40]
  lr_decay_rate: 0.1
  batch_size:  64
  max_epochs: 300
  early_stop: 30
  use_cl: False
  cl_step_size: 2300
  model_args:
    num_nodes: 716
    in_dim:  3
    model_dim:  128
    time:  96
    in_len:  12
    out_len:  12
    num_heads:  4
    pool_size:  128
    attn_drop:  0.1
    proj_drop:  0.15

GBA:
  num_nodes: 2352
  in_steps: 12
  out_steps: 12

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  day_of_week: True
  
  lr: 0.001
  weight_decay: 0.0001
  milestones: [15, 30, 40]
  lr_decay_rate: 0.1
  batch_size:  64
  max_epochs: 300
  early_stop: 30
  use_cl: False
  cl_step_size: 2300
  model_args:
    num_nodes: 2352
    in_dim:  3
    model_dim:  128
    time:  96
    in_len:  12
    out_len:  12
    num_heads:  4
    pool_size:  16
    attn_drop:  0.1
    proj_drop:  0.15

CA:
  num_nodes: 8600
  in_steps: 12
  out_steps: 12
  in_dim:  3

  train_size: 0.6
  val_size: 0.2

  time_of_day: True
  day_of_week: True
  
  lr: 0.001
  weight_decay: 0.0001
  milestones: [15, 30, 40]
  lr_decay_rate: 0.1
  batch_size:  32
  max_epochs: 300
  early_stop: 30
  use_cl: False
  cl_step_size: 2300
  model_args:
    num_nodes: 8600
    in_dim:  3
    model_dim:  128
    time:  96
    in_len:  12
    out_len:  12
    num_heads:  4
    pool_size:  128
    attn_drop:  0.1
    proj_drop:  0.15